# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container: pomeo/node.js:latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache npm
        id: npm-cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: v1-npm-deps-${{ hashFiles('**/package-lock.json') }}
          restore-keys: v1-npm-deps-
      - name: Cache dependencies
        id: modules
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        if: steps.modules.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts
      - run: npm run test
